### ISSUE TITLE
TTT sometimes stops working and game freezes

### ISSUE THREAD

**Issue by Quezako** [karashiiro/TextToTalk#41] opened 2021-08-06 20:57 UTC
Hello,

I've uninstalled the TTT plugin and removed the settings, but I still have the problem.
Sometimes, after on sentence read successfully, the TTT plugin stops working.
Then , if I try to disable it or to exit the game, the game freezes.

I never had the problem before, but I've switched to Windows 11 recently, on a new computer.
I'm using the standard Windows voices.
It seems to happen when I alt-tab on Chrome.

EDIT:
When I type /xldebug and I open log window in verbose mod, then I launch a dialog, I have the following message:
"Unhandled SetStringChunkType: 16" a lot of times, then the same message with 29, 19, 41, 19, etc.

EDIT 2:
after uninstalling all plugins and installing TTT fresh, it seems to be more stable now. So I suppose that there was a conflict with another plugin or setting.

**Comment by Ahegaoa** [comment] 2021-08-10 00:41
Same thing happened to me and I am using Windows 10 and other dalamud plugins, also using testing version 1.8.1 of TTT.

**Comment by ryankhart** [comment] 2021-08-10 01:59
Oh, I'm so glad it's not just me. Windows 10 here. I also have other plugins installed as well. 33 of them to be exact.

My steps to reproduce the game crash are the exact same. At some point, usually when progressing through many cutscenes without much break, TTT stops working at all as if it were not installed or enabled. Previously when it did this, I could solve it by disabling it and reenabling it from the installed plugins tab. But now, it just crashes the whole game.

It sounds to me like there's a plugin incompatibility. If it proves helpful, here is a list of all of my plugins, by their directory name in my "installedPlugins" directory.

```
AdventurerInNeed
AutoVisor
BetterPartyFinder
BrowserHost.Plugin
ChatBubbles
Dalamud.LoadingImage
Dalamud.RichPresence
EasyEyes
FCNameColor
FPSPlugin
GentleTouch
GoodMemory
ItemSearchPlugin
MacroRecursion
MapLinker
MarketBoardPlugin
MiniCactpotSolver
NamePlateDebuffs
NoSoliciting
orchestrion
PeepingTom
PennyPincher
PingPlugin
PlayerTrack
PriceCheck
Quest Map
RezPls
SideHUDPlugin
SimpleTweaksPlugin
SlideCast
SoundSetter
TextToTalk
TheGreatSeparator
Tourist
WondrousTailsSolver
```

**Comment by karashiiro** [comment] 2021-08-10 03:44
Could any of you try and isolate the issue? Like removing half of your plugins besides TextToTalk, then seeing if it goes away, and then removing half of the remainder if it doesn't, etc. until the plugin is identified. None of those plugins seem like they would have anything to do with this unless they're messing with threads in a way that affects other plugins for some reason.

**Comment by ryankhart** [comment] 2021-08-10 17:01
Ok, it happened again.

Something I noticed and will test to confirm in the future is whether or not the existence of "..." in the dialogue causes this issue. The last dialogue that worked had a "..." in it. I don't know if that's a silly thing to test, but I don't know how to code works, so I don't want to entirely rule it out.

Next, I'll restore my backed-up plugins and delete the other half, save for the TTT plugin.

**Comment by karashiiro** [comment] 2021-08-10 17:10
That could be an issue? No clue, but I just tossed a replacement for that (… -> ...) into v1.8.2 anyways.

**Comment by ryankhart** [comment] 2021-08-10 17:28
Ok, I have more info, and I'm able to reproduce the problem with a single dialogue every time with _**no other plugins installed**_.

It happens when I talk to an NPC who says nothing but "...". And I checked in the chat window whether it was an ellipsis (…) or just 3 periods, and it seemed to be three periods because they were each 3 separate characters when selecting.

The point that I'm at in the MSQ is just before accepting the MSQ quest called "An Ending to Mark a New Beginning". And the NPC that triggers the problem by saying "..." is Thancred.

And lastly, another important part: I was experiencing this problem when using Amazon Polly. So I tested whether or not I can reproduce the bug with system voices instead of Amazon Polly, and I could not reproduce the bug with the above steps. So, it appears to be exclusively an issue with Amazon Polly when being fed text that only contains 3 periods ("..."). At least that's my impression of my testing here.

**Comment by karashiiro** [comment] 2021-08-10 17:42
Is it specifically when there is only three periods, or is it in any text with three periods? It sounds like the API might be rejecting the input when the text is unspeakable.

**Comment by ryankhart** [comment] 2021-08-10 18:03
Ok, this is getting strange. First to answer your question. While Amazon Polly was enabled, yes, TTT only stopped working when the dialogue was nothing but 3 periods.

However, when I switched to system voices, I had no problems with all system voices except for `Microsoft Zira Desktop (EN)`. With that voice, it seems that all dialogue gave this error dialog box shown below in two separate instances. But this seems like an entirely different issue to me.

I still have yet to reproduce the silent issue of TTT stopping from working while the game continues to run fine until you (a) try to disable the plugin or (b) try to exit the game normally.

![image](https://user-images.githubusercontent.com/3673962/128908936-783cbff2-9743-47df-9bdb-32b781fb3c47.png)
![image](https://user-images.githubusercontent.com/3673962/128909442-6d8c7fa2-a94d-4b15-bfbf-bac5f0e6b8dd.png)

**Comment by karashiiro** [comment] 2021-08-10 18:13
Let me know if you're able to reproduce it - in the meantime, I added a fix for some of those issues that skips TTS for unspeakable inputs. That should fix issues with Polly and Zira Desktop, since "..." just won't be queued at all.

**Comment by ryankhart** [comment] 2021-08-10 18:18
To be clear, while I was testing system voices, for this issue, Zira Desktop gave the above error for all dialogue, not just dialogue that only contained "...".

**Comment by ryankhart** [comment] 2021-08-10 23:12
The latest test build of 1.8.2 fixes the Amazon Polly issue where NPCs who only say "..." cause TTT to stop working! Thanks for the update on that!

The Zira Desktop system voice issue still persists, although that might just be something funky that is unique to my system and is also entirely avoidable because there are plenty of alternative voices to choose from.

Originally, I thought I had to wait until 1.8.2 got merged into the official repository. So I stepped away for a while. When I came back and it still wasn't merged, I thought I would attempt to download the zip file you submitted and manually place those files in my installedPlugins directory. It worked and was simpler than I expected.

I also suspect that I may have hijacked @Quezako's issue thread here because he reported this issue on system voices, but that uninstalling other plugins worked. So it remains to be seen if this issue is resolved for him yet.

**Closed** 2021-09-04 05:43 UTC
Labels: bug
