### ISSUE TITLE
TextToTalk not installing and gives an error when trying to install and an error after restarting

### ISSUE THREAD

**Issue by Astorec** [karashiiro/TextToTalk#166] opened 2023-07-03 18:46 UTC
# Summary

I came across this plugin the other day and wanted to give it a try. Whilst trying to install it it comes up saying that it failed to install and restart the game to try again/contact if it continues. So following that after the restart it comes up saying that the plugin failed to load. I've copied the logs for this and pasted below. I'll also note that I'm using Pop OS but I'm not sure how much  that would effect plugins as this is the first time I've ran in to the issue.

# Log Message
```
LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0wNy0wM1QxOTozNzozOS40MjY5MzIyKzAxOjAwIiwiSW5mbyI6IlN5c3RlbS5SZWZsZWN0aW9uLlJlZmxlY3Rpb25UeXBlTG9hZEV4Y2VwdGlvbjogVW5hYmxlIHRvIGxvYWQgb25lIG9yIG1vcmUgb2YgdGhlIHJlcXVlc3RlZCB0eXBlcy5cclxuQ291bGQgbm90IGxvYWQgZmlsZSBvciBhc3NlbWJseSAnU3lzdGVtLk5ldC5IdHRwLCBWZXJzaW9uPTcuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49YjAzZjVmN2YxMWQ1MGEzYScuIEluY29ycmVjdCBhbGlnbm1lbnQuICgweDgwMDcwNDZDKVxyXG4gICBhdCBTeXN0ZW0uUmVmbGVjdGlvbi5SdW50aW1lTW9kdWxlLkdldFR5cGVzKFJ1bnRpbWVNb2R1bGUgbW9kdWxlKVxyXG4gICBhdCBTeXN0ZW0uUmVmbGVjdGlvbi5Bc3NlbWJseS5HZXRUeXBlcygpXHJcbiAgIGF0IERhbGFtdWQuUGx1Z2luLkludGVybmFsLlR5cGVzLkxvY2FsUGx1Z2luLi5jdG9yKEZpbGVJbmZvIGRsbEZpbGUsIExvY2FsUGx1Z2luTWFuaWZlc3QgbWFuaWZlc3QpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFBsdWdpblxcSW50ZXJuYWxcXFR5cGVzXFxMb2NhbFBsdWdpbi5jczpsaW5lIDg3XHJcblN5c3RlbS5JTy5GaWxlTG9hZEV4Y2VwdGlvbjogQ291bGQgbm90IGxvYWQgZmlsZSBvciBhc3NlbWJseSAnU3lzdGVtLk5ldC5IdHRwLCBWZXJzaW9uPTcuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49YjAzZjVmN2YxMWQ1MGEzYScuIEluY29ycmVjdCBhbGlnbm1lbnQuICgweDgwMDcwNDZDKVxyXG5GaWxlIG5hbWU6ICdTeXN0ZW0uTmV0Lkh0dHAsIFZlcnNpb249Ny4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iMDNmNWY3ZjExZDUwYTNhJ1xyXG4gLS0tPiBTeXN0ZW0uSU8uRmlsZUxvYWRFeGNlcHRpb246IENvdWxkIG5vdCBsb2FkIGZpbGUgb3IgYXNzZW1ibHkgJ1N5c3RlbS5OZXQuSHR0cCwgVmVyc2lvbj03LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EnLiBJbmNvcnJlY3QgYWxpZ25tZW50LiAoMHg4MDA3MDQ2QylcclxuRmlsZSBuYW1lOiAnU3lzdGVtLk5ldC5IdHRwLCBWZXJzaW9uPTcuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49YjAzZjVmN2YxMWQ1MGEzYSdcclxuIC0tLT4gU3lzdGVtLlJ1bnRpbWUuSW50ZXJvcFNlcnZpY2VzLkNPTUV4Y2VwdGlvbiAoMHg4MDA3MDQ2Qyk6IEluY29ycmVjdCBhbGlnbm1lbnQuICgweDgwMDcwNDZDKVxyXG4gICBhdCBTeXN0ZW0uUnVudGltZS5Mb2FkZXIuQXNzZW1ibHlMb2FkQ29udGV4dC5JbnRlcm5hbExvYWQoUmVhZE9ubHlTcGFuYDEgYXJyQXNzZW1ibHksIFJlYWRPbmx5U3BhbmAxIGFyclN5bWJvbHMpXHJcbiAgIGF0IFN5c3RlbS5SdW50aW1lLkxvYWRlci5Bc3NlbWJseUxvYWRDb250ZXh0LkxvYWRGcm9tU3RyZWFtKFN0cmVhbSBhc3NlbWJseSwgU3RyZWFtIGFzc2VtYmx5U3ltYm9scylcclxuICAgYXQgRGFsYW11ZC5QbHVnaW4uSW50ZXJuYWwuTG9hZGVyLk1hbmFnZWRMb2FkQ29udGV4dC5Mb2FkQXNzZW1ibHlGcm9tRmlsZVBhdGgoU3RyaW5nIHBhdGgpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFBsdWdpblxcSW50ZXJuYWxcXExvYWRlclxcTWFuYWdlZExvYWRDb250ZXh0LmNzOmxpbmUgMTE1XHJcbiAgIGF0IERhbGFtdWQuUGx1Z2luLkludGVybmFsLkxvYWRlci5NYW5hZ2VkTG9hZENvbnRleHQuTG9hZChBc3NlbWJseU5hbWUgYXNzZW1ibHlOYW1lKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxQbHVnaW5cXEludGVybmFsXFxMb2FkZXJcXE1hbmFnZWRMb2FkQ29udGV4dC5jczpsaW5lIDE5MlxyXG4gICBhdCBTeXN0ZW0uUnVudGltZS5Mb2FkZXIuQXNzZW1ibHlMb2FkQ29udGV4dC5SZXNvbHZlVXNpbmdMb2FkKEFzc2VtYmx5TmFtZSBhc3NlbWJseU5hbWUpXHJcbiAgIGF0IFN5c3RlbS5SdW50aW1lLkxvYWRlci5Bc3NlbWJseUxvYWRDb250ZXh0LlJlc29sdmUoSW50UHRyIGdjaE1hbmFnZWRBc3NlbWJseUxvYWRDb250ZXh0LCBBc3NlbWJseU5hbWUgYXNzZW1ibHlOYW1lKSIsIkNvbnRleHQiOiJbTE9DQUxQTFVHSU5dIENvdWxkIG5vdCBsb2FkIG9uZSBvciBtb3JlIHR5cGVzIHdoZW4gc2VhcmNoaW5nIGZvciBJRGFsYW11ZFBsdWdpbjogWjpcXGhvbWVcXGFzdG9yZWNcXC54bGNvcmVcXGluc3RhbGxlZFBsdWdpbnNcXFRleHRUb1RhbGtcXDEuMjIuMC4wXFxUZXh0VG9UYWxrLmRsbCJ9
2023-07-03 19:37:39.354 +01:00 [ERR] [LOCALPLUGIN] Could not load one or more types when searching for IDalamudPlugin: Z:\home\astorec\.xlcore\installedPlugins\TextToTalk\1.22.0.0\TextToTalk.dll
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Incorrect alignment. (0x8007046C)
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Dalamud.Plugin.Internal.Types.LocalPlugin..ctor(FileInfo dllFile, LocalPluginManifest manifest) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 87
System.IO.FileLoadException: Could not load file or assembly 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Incorrect alignment. (0x8007046C)
File name: 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
 ---> System.IO.FileLoadException: Could not load file or assembly 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Incorrect alignment. (0x8007046C)
File name: 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
 ---> System.Runtime.InteropServices.COMException (0x8007046C): Incorrect alignment. (0x8007046C)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.LoadAssemblyFromFilePath(String path) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Loader\ManagedLoadContext.cs:line 115
   at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.Load(AssemblyName assemblyName) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Loader\ManagedLoadContext.cs:line 192
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
2023-07-03 19:37:39.438 +01:00 [INF] [LOCALPLUGIN] Loading TextToTalk.dll
2023-07-03 19:37:39.442 +01:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0wNy0wM1QxOTozNzozOS40NDIzMTM1KzAxOjAwIiwiSW5mbyI6IlN5c3RlbS5SZWZsZWN0aW9uLlRhcmdldEludm9jYXRpb25FeGNlcHRpb246IEV4Y2VwdGlvbiBoYXMgYmVlbiB0aHJvd24gYnkgdGhlIHRhcmdldCBvZiBhbiBpbnZvY2F0aW9uLlxyXG4gLS0tPiBTeXN0ZW0uSU8uRmlsZUxvYWRFeGNlcHRpb246IENvdWxkIG5vdCBsb2FkIGZpbGUgb3IgYXNzZW1ibHkgJ1N5c3RlbS5OZXQuSHR0cCwgVmVyc2lvbj03LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EnLiBJbmNvcnJlY3QgYWxpZ25tZW50LiAoMHg4MDA3MDQ2QylcclxuRmlsZSBuYW1lOiAnU3lzdGVtLk5ldC5IdHRwLCBWZXJzaW9uPTcuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49YjAzZjVmN2YxMWQ1MGEzYSdcclxuIC0tLT4gU3lzdGVtLlJ1bnRpbWUuSW50ZXJvcFNlcnZpY2VzLkNPTUV4Y2VwdGlvbiAoMHg4MDA3MDQ2Qyk6IEluY29ycmVjdCBhbGlnbm1lbnQuICgweDgwMDcwNDZDKVxyXG4gICBhdCBUZXh0VG9UYWxrLlRleHRUb1RhbGsuLmN0b3IoRGFsYW11ZFBsdWdpbkludGVyZmFjZSBwaSwgS2V5U3RhdGUga2V5U3RhdGUsIENoYXRHdWkgY2hhdCwgRnJhbWV3b3JrIGZyYW1ld29yaywgQ2xpZW50U3RhdGUgY2xpZW50U3RhdGUsIEdhbWVHdWkgZ3VpLCBEYXRhTWFuYWdlciBkYXRhLCBPYmplY3RUYWJsZSBvYmplY3RzLCBDb25kaXRpb24gY29uZGl0aW9uLCBDb21tYW5kTWFuYWdlciBjb21tYW5kTWFuYWdlciwgU2lnU2Nhbm5lciBzaWdTY2FubmVyKVxyXG4gICBhdCBTeXN0ZW0uUnVudGltZU1ldGhvZEhhbmRsZS5JbnZva2VNZXRob2QoT2JqZWN0IHRhcmdldCwgVm9pZCoqIGFyZ3VtZW50cywgU2lnbmF0dXJlIHNpZywgQm9vbGVhbiBpc0NvbnN0cnVjdG9yKVxyXG4gICBhdCBTeXN0ZW0uUmVmbGVjdGlvbi5Db25zdHJ1Y3Rvckludm9rZXIuSW52b2tlKE9iamVjdCBvYmosIEludFB0ciogYXJncywgQmluZGluZ0ZsYWdzIGludm9rZUF0dHIpXHJcbiAgIC0tLSBFbmQgb2YgaW5uZXIgZXhjZXB0aW9uIHN0YWNrIHRyYWNlIC0tLVxyXG4gICBhdCBTeXN0ZW0uUmVmbGVjdGlvbi5Db25zdHJ1Y3Rvckludm9rZXIuSW52b2tlKE9iamVjdCBvYmosIEludFB0ciogYXJncywgQmluZGluZ0ZsYWdzIGludm9rZUF0dHIpXHJcbiAgIGF0IFN5c3RlbS5SZWZsZWN0aW9uLlJ1bnRpbWVDb25zdHJ1Y3RvckluZm8uSW52b2tlV2l0aE1hbnlBcmd1bWVudHMoUnVudGltZUNvbnN0cnVjdG9ySW5mbyBjaSwgSW50MzIgYXJnQ291bnQsIE9iamVjdCBvYmosIEJpbmRpbmdGbGFncyBpbnZva2VBdHRyLCBCaW5kZXIgYmluZGVyLCBPYmplY3RbXSBwYXJhbWV0ZXJzLCBDdWx0dXJlSW5mbyBjdWx0dXJlKVxyXG4gICBhdCBTeXN0ZW0uUmVmbGVjdGlvbi5SdW50aW1lQ29uc3RydWN0b3JJbmZvLkludm9rZShPYmplY3Qgb2JqLCBCaW5kaW5nRmxhZ3MgaW52b2tlQXR0ciwgQmluZGVyIGJpbmRlciwgT2JqZWN0W10gcGFyYW1ldGVycywgQ3VsdHVyZUluZm8gY3VsdHVyZSlcclxuICAgYXQgU3lzdGVtLlJlZmxlY3Rpb24uTWV0aG9kQmFzZS5JbnZva2UoT2JqZWN0IG9iaiwgT2JqZWN0W10gcGFyYW1ldGVycylcclxuICAgYXQgRGFsYW11ZC5Jb0MuSW50ZXJuYWwuU2VydmljZUNvbnRhaW5lci5DcmVhdGVBc3luYyhUeXBlIG9iamVjdFR5cGUsIE9iamVjdFtdIHNjb3BlZE9iamVjdHMsIElTZXJ2aWNlU2NvcGUgc2NvcGUpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXElvQ1xcSW50ZXJuYWxcXFNlcnZpY2VDb250YWluZXIuY3M6bGluZSAxMzRcclxuICAgYXQgRGFsYW11ZC5QbHVnaW4uSW50ZXJuYWwuVHlwZXMuTG9jYWxQbHVnaW4uTG9hZEFzeW5jKFBsdWdpbkxvYWRSZWFzb24gcmVhc29uLCBCb29sZWFuIHJlbG9hZGluZykgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcUGx1Z2luXFxJbnRlcm5hbFxcVHlwZXNcXExvY2FsUGx1Z2luLmNzOmxpbmUgNDY5IiwiQ29udGV4dCI6IltMT0NBTFBMVUdJTl0gRXJyb3Igd2hpbGUgbG9hZGluZyBUZXh0VG9UYWxrIn0=
2023-07-03 19:37:39.441 +01:00 [ERR] [LOCALPLUGIN] Error while loading TextToTalk
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileLoadException: Could not load file or assembly 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Incorrect alignment. (0x8007046C)
File name: 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
 ---> System.Runtime.InteropServices.COMException (0x8007046C): Incorrect alignment. (0x8007046C)
   at TextToTalk.TextToTalk..ctor(DalamudPluginInterface pi, KeyState keyState, ChatGui chat, Framework framework, ClientState clientState, GameGui gui, DataManager data, ObjectTable objects, Condition condition, CommandManager commandManager, SigScanner sigScanner)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.InvokeWithManyArguments(RuntimeConstructorInfo ci, Int32 argCount, Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 134
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 469
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 1352
2023-07-03 19:37:39.443 +01:00 [INF] [PLUGINM] Regular plugin failed to load, adding anyways: TextToTalk.dll
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileLoadException: Could not load file or assembly 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Incorrect alignment. (0x8007046C)
File name: 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
 ---> System.Runtime.InteropServices.COMException (0x8007046C): Incorrect alignment. (0x8007046C)
   at TextToTalk.TextToTalk..ctor(DalamudPluginInterface pi, KeyState keyState, ChatGui chat, Framework framework, ClientState clientState, GameGui gui, DataManager data, ObjectTable objects, Condition condition, CommandManager commandManager, SigScanner sigScanner)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.InvokeWithManyArguments(RuntimeConstructorInfo ci, Int32 argCount, Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 134
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 469
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 1352
```

**Comment by karashiiro** [comment] 2023-07-09 18:51
Duplicate of #151 (just renamed that issue for clarity). The error is slightly different, but it's with the same file and makes just as little sense. `System.Net.Http` is provided in the bundled runtime that Dalamud ships with, so it's unclear how this can happen.

**Closed by karashiiro** 2023-07-09 18:51 UTC
Labels: duplicate

**Comment by Astorec** [comment] 2023-07-09 19:31
> Duplicate of #151 (just renamed that issue for clarity). The error is slightly different, but it's with the same file and makes just as little sense. `System.Net.Http` is provided in the bundled runtime that Dalamud ships with, so it's unclear how this can happen.

Ahhh okay, that is weird. Baseed on that I've tried a couple of things to try and get it working such as clearning off the Dalamud files via XIVLauncher and what not. I'll do some further digging if I can then and see where it leads me. Thanks for the Response!
