### ISSUE TITLE
TTS repeated twice in most dialogues

### ISSUE THREAD

**Issue by Ahegaoa** [karashiiro/TextToTalk#40] opened 2021-08-04 08:22 UTC
I am using testing version 1.8.0.4 and many of the dialogues are read twice. I am using Amazon Polly Neural Engine and its only free for 1 million characters, not sure if repeated speech is counted or not.

**Comment by Noshei** [comment] 2021-08-09 02:39
I'm also getting this with windows speech engine.  I think I've noticed a pattern, but not positive.  I've had this happen at least a couple times when a single line of dialog carries over to a second chat "page".  I'm not positive that this is 100% the cause, so I'll keep trying to find a commonality.

**Comment by karashiiro** [comment] 2021-08-09 04:57
Linking https://discord.com/channels/581875019861328007/684745859497590843/874124148266381322 for reference, this seems to be the issue
![image](https://user-images.githubusercontent.com/49822414/128661871-d658623d-ae22-4cc2-a88e-cd05529e9a2b.png)

**Comment by karashiiro** [comment] 2021-08-10 03:39
Possible fix coming in this testing release https://github.com/goatcorp/DalamudPlugins/pull/1000

**Comment by karashiiro** [comment] 2021-08-13 00:08
Merged into testing, let me know if it works 👍

**Comment by Ahegaoa** [comment] 2021-08-17 00:09
Thank you it works.. no more duplicate speech.

**Closed** 2021-08-17 00:23 UTC
Labels: bug
