### ISSUE TITLE
1.8.0.1 Bugs

### ISSUE THREAD

**Issue by johnysandels** [karashiiro/TextToTalk#36] opened 2021-07-23 20:09 UTC
-Deleting plugin in plugin installer runs into an error
![installer error](https://user-images.githubusercontent.com/79720646/126835862-af032202-7fa6-4cd4-8227-69be953c41c7.png)

- /echo chat doesn't trigger TTS when it's supposed to.

**Comment by karashiiro** [comment] 2021-07-23 20:24
Can you be more specific on the /echo thing? I thought I was able to replicate this, but it turned out that the Echo chat type was just disabled.

**Comment by karashiiro** [comment] 2021-07-23 20:25
Also, can you provide an error from the log for the deleting the plugin?

**Comment by johnysandels** [comment] 2021-07-23 20:29
Yeah definitely!

[dalamud.log](https://github.com/karashiiro/TextToTalk/files/6871084/dalamud.log)

**Comment by karashiiro** [comment] 2021-07-23 20:36
That one's fixed, will merge with https://github.com/goatcorp/DalamudPlugins/pull/971, no clue on the /echo issue yet, though.

**Comment by johnysandels** [comment] 2021-07-23 20:42
Just checked echo, I turned it on and the first messages worked and all messages after didn't work.

**Comment by karashiiro** [comment] 2021-07-23 20:43
Might be related to #37? If so we should revisit this one after 1.8.0.2 is merged.

**Comment by johnysandels** [comment] 2021-07-23 20:45
This is with my lexicons disabled. It might have something to do with #35 and the queue order. I can load it up tonight to see if it's fixed.

**Comment by karashiiro** [comment] 2021-07-24 01:11
My PR is still open, so I'll just drop this here in case you happen to have time for it 🙂 

[latest.zip](https://github.com/karashiiro/TextToTalk/files/6871718/latest.zip)

**Comment by johnysandels** [comment] 2021-07-24 04:09
Deleting the plugin is fixed, echo is fixed. text queueing is working at expected. 

chat text triggered between dialogue boxes uses the gendered voice of the dialogue speaker.

When disabling the plugin by toggle, chat speech was stopped, and the first dialogue speech was stopped, but the second dialogue box read out.

Also your revert to reset the speaker mentioned in #35, is either not part of this update, or I was able to make it work.

**Comment by karashiiro** [comment] 2021-07-24 19:33
The speaker reset works for me, but I'll look into it further just in case. The other issues seem to be caused by the system backend not always responding to speech cancellation requests - the Polly backend doesn't seem to have these issues. Looking into that right now.

**Comment by johnysandels** [comment] 2021-07-24 19:57
For me it resets once the final dialogue box is closed, but doesn't reset between dialogue boxes.

**Comment by karashiiro** [comment] 2021-07-24 20:06
For me it's the exact opposite 😄 I think that it's really just a result of how much time is being spent between dialogue advances, though.

**Comment by karashiiro** [comment] 2021-07-24 20:06
I think I finally have a fix, will drop a link in a minute.

**Comment by karashiiro** [comment] 2021-07-24 20:12
[latest.zip](https://github.com/karashiiro/TextToTalk/files/6873017/latest.zip)

Here's the new build I'm PRing, let me know how it works 👍

**Comment by johnysandels** [comment] 2021-07-24 20:25
I've just checked all of those bugs, and it seems like everything is working!
Beautiful work!

**Closed** 2021-07-24 20:33 UTC
Labels: bug
