### ISSUE TITLE
TextToTalk Error

### ISSUE THREAD

**Issue by Ahegaoa** [karashiiro/TextToTalk#6] opened 2021-04-28 22:17 UTC
After installing the plugin and attempting to open the configuration window by clicking on the config button, i get this error popup:
https://i.imgur.com/F4T0atz.png

I tried restarting the game but didn't work. Please advise.

**Comment by karashiiro** [comment] 2021-04-28 22:20
Please send your `dalamud.log` from `%appdata%\XIVLauncher\` so we can see what the problem is.

![](https://cdn.discordapp.com/attachments/687530726756712478/810897701864210472/explorer_2021-02-08_19-20-41.png)

**Comment by Ahegaoa** [comment] 2021-04-28 22:30
[dalamud.log](https://github.com/karashiiro/TextToTalk/files/6395161/dalamud.log)

**Comment by karashiiro** [comment] 2021-04-28 22:35
Try deleting the plugin configuration at `%appdata%/XIVLauncher/pluginConfigs/TextToTalk.json`. It looks like a trigger or an exclusion is broken?

**Comment by Ahegaoa** [comment] 2021-04-28 22:46
same error.

**Comment by karashiiro** [comment] 2021-04-28 23:06
Do you have any voice packages installed? It might do this if you don't have any.

![Screenshot 2021-04-28 160451](https://user-images.githubusercontent.com/49822414/116483243-91590800-a83b-11eb-95f4-e2dca36a5e2b.png)

**Comment by Ahegaoa** [comment] 2021-04-28 23:13
I have amazon polly voices installed beside the English (United States) ones, amazon polly voices don't show up in this config panel though but in the old speech config panel, will show both:
new: https://i.imgur.com/F8mEIgu.png
old: https://i.imgur.com/DouTYNe.png

**Comment by karashiiro** [comment] 2021-04-29 17:19
Just got an update merged, let me know if this still happens after updating.

**Comment by Ahegaoa** [comment] 2021-04-29 21:03
It is working now, thank you so much. It also detected my amazon polly voices.

**Closed** 2021-04-29 21:08 UTC
Labels: bug
