### ISSUE TITLE
the TTS will talk as soon as something pop up on a screen even if it mean to talk over it self

### ISSUE THREAD

**Issue by masterkiller332** [karashiiro/TextToTalk#28] opened 2021-07-06 22:08 UTC
the TTS will talk as soon as something pop up on a screen even if it mean to talk over it self

**Comment by karashiiro** [comment] 2021-07-06 22:43
Probably a duplicate of #26, this will be fixed with https://github.com/goatcorp/DalamudPlugins/pull/949

**Closed** 2021-07-11 21:17 UTC
Labels: bug
