### ISSUE TITLE
TTS Pronunciation Corrections Editor

### ISSUE THREAD

**Issue by zbee** [karashiiro/TextToTalk#71] opened 2022-01-10 18:48 UTC
An editor similar to ACT's TTS options would be amazing, see an example of this below that corrects the pronunciation of 'Regen' when it's cast on me.

Just a tab that lets users input text to match, and it's corrected pronunciation.

![image](https://user-images.githubusercontent.com/1582821/148821430-c9deff05-dc02-4c32-845b-ebf97b23e2c5.png)

**Comment by karashiiro** [comment] 2022-01-10 18:49
Duplicate of #63, but it's good to hear that other people are thinking about this too 😄

**Closed by karashiiro** 2022-01-10 18:49 UTC
Labels: duplicate, enhancement

**Comment by zbee** [comment] 2022-01-10 18:55
And now I understand what those Lexicons are ha - thank you!

**Comment by johnysandels** [comment] 2022-01-10 21:43
> And now I understand what those Lexicons are ha - thank you!


Yeah the fix for character names and Locations is in one file, and miscellaneous is just a fix on general words.
