### ISSUE TITLE
Installation fails on Mac systems

### ISSUE THREAD

**Issue by 0xChief** [karashiiro/TextToTalk#83] opened 2022-03-17 21:30 UTC
So the XIV on Mac launcher has support for Dalamud which is how I'm attempting to install TextToTalk

On Mac, I get the `failed to install plugin error. Please restart your game and try again` error. I can install other plugins but TTS won't ever work. 

Has anyone had any success with getting TTS on Mac for FF14?

**Comment by karashiiro** [comment] 2022-03-28 02:01
Seems the issue is that it's trying to load the System (Windows) voice synthesizer the first time it's installed, so it instantly fails. I'll release a fix later tonight.

**Comment by karashiiro** [comment] 2022-03-28 03:02
Should be fixed, now.

**Closed** 2022-03-30 02:52 UTC
Labels: bug

**Comment by 0xChief** [comment] 2022-09-04 14:16
Bumping this to mention that I still get the failure to install message. Same situation, using XIV on Mac and attempting to install TextToTalk.
